repos:
- repo: local
  hooks:
    - id: alejandra
      name: alejandra
      entry: alejandra
      language: system
      files: \.nix$
    - id: statix
      name: statix
      entry: statix check
      language: system
      files: \.nix$
